### PR TITLE
Closed days fix ipp

### PR DESCRIPTION
**Pull request by raabf**
This PR allows the parser to work when there are empty columns due to closed days.

I'm not sure, if pdf-to-text always correcty perserves the indents on multiple lines, but this fix works fine for my test files. It correctly detects all menus for all days which are non empty and those who are empty are correctly not created, so I think this fix works.

As test files I used the last two weeks, which were quite holiday intensive (see attachment), and luckily we can test this implementation the next weeks, which are full of holidays again.

[KW-18_30.04.-04.05.18.pdf](https://github.com/srehwald/eat-api/files/1996045/KW-18_30.04.-04.05.18.pdf)
[KW-19_07.05.-11.05.18.pdf](https://github.com/srehwald/eat-api/files/1996047/KW-19_07.05.-11.05.18.pdf)

### CODE REVIEW

**Comment by srehwald** [comment]
I think your code is fine, thanks for your work! If you have the time, could you add one or both pdfs as a test case (in `test_menu_parser.py`)? This would proof that it really works for those files. If so, please convert them to a .txt file using the pdftotext command as in the code (should be `pdftotext -layout<input.pdf> <output.txt>`) and add that to the repository (instead of the pdf).

**Comment by raabf** [comment]
> "Program testing can be a very effective way to show the presence of bugs, but is hopelessly inadequate for showing their absence."
– Edsger Wybe Dijkstra

:stuck_out_tongue: Although, my tests do no prove the correctness of my code, they are extraordinary useful :satisfied:, so I added both weeks (especially they test two cases: a week with one holiday and even a week with two holidays)

**Comment by srehwald** [comment]
Obviously, you are right 😀 I should probably rephrase my request for test cases. Anyway, thanks a lot for your contribution!

**Comment by srehwald** [comment]
@raabf I had to revert your pull request since it causes an error for last weeks menu. Didn't test for that immediately 🙈 . I'd love to merge your changes again once this is fixed.

`Traceback (most recent call last):
  File "src/main.py", line 120, in <module>
    main()
  File "src/main.py", line 79, in main
    menus = parser.parse(location)
  File "/Users/simon/Downloads/eat-api-closed-days-fix-ipp/src/menu_parser.py", line 324, in parse
    parsed_menus = self.get_menus(data, year, week_number)
  File "/Users/simon/Downloads/eat-api-closed-days-fix-ipp/src/menu_parser.py", line 355, in get_menus
    pos_fri = positions[4][0]
IndexError: list index out of range`

**Pull request merged**
